name:                 ndvi-backend
version:              0.1.0.0
visibility:           public
id:                   ndvi-backend-0.1.0.0-KssvLUgBSs11vWe6AxGvC7
key:                  ndvi-backend-0.1.0.0-KssvLUgBSs11vWe6AxGvC7
synopsis:             NDVI Analysis Backend with Lazy Evaluation
abi:                  00ca4f20a6d6f6b4c38be955972a6ac8
exposed:              True
exposed-modules:      Ndvi Types
hidden-modules:       Paths_ndvi_backend
import-dirs:
    "/Users/keermanipamisetty/Desktop/NDVI ANALYSIS/backend/.stack-work/install/aarch64-osx/2ad67822f177c4de4acf7e19b26519c713ed91bc5171365321467f2f3a5e7417/9.4.8/lib/aarch64-osx-ghc-9.4.8/ndvi-backend-0.1.0.0-KssvLUgBSs11vWe6AxGvC7"

library-dirs:
    "/Users/keermanipamisetty/Desktop/NDVI ANALYSIS/backend/.stack-work/install/aarch64-osx/2ad67822f177c4de4acf7e19b26519c713ed91bc5171365321467f2f3a5e7417/9.4.8/lib/aarch64-osx-ghc-9.4.8/ndvi-backend-0.1.0.0-KssvLUgBSs11vWe6AxGvC7"

library-dirs-static:
    "/Users/keermanipamisetty/Desktop/NDVI ANALYSIS/backend/.stack-work/install/aarch64-osx/2ad67822f177c4de4acf7e19b26519c713ed91bc5171365321467f2f3a5e7417/9.4.8/lib/aarch64-osx-ghc-9.4.8/ndvi-backend-0.1.0.0-KssvLUgBSs11vWe6AxGvC7"

dynamic-library-dirs:
    "/Users/keermanipamisetty/Desktop/NDVI ANALYSIS/backend/.stack-work/install/aarch64-osx/2ad67822f177c4de4acf7e19b26519c713ed91bc5171365321467f2f3a5e7417/9.4.8/lib/aarch64-osx-ghc-9.4.8"

data-dir:
    "/Users/keermanipamisetty/Desktop/NDVI ANALYSIS/backend/.stack-work/install/aarch64-osx/2ad67822f177c4de4acf7e19b26519c713ed91bc5171365321467f2f3a5e7417/9.4.8/share/aarch64-osx-ghc-9.4.8/ndvi-backend-0.1.0.0"

hs-libraries:         HSndvi-backend-0.1.0.0-KssvLUgBSs11vWe6AxGvC7
depends:
    aeson-2.1.2.1-JbCTFV6Xk1ECJSbwVZEkyY base-4.17.2.1
    bytestring-0.11.5.3 cassava-0.5.3.0-DN2f5bRXXps1x7kbWfKDkX
    directory-1.3.7.1 filepath-1.4.2.2
    http-types-0.12.4-Cfm4yRPRlyrAemJjZB5LMT
    scotty-0.12.1-IN3Z8TiBvPwHoEedZXEzRE text-2.0.2
    vector-0.13.1.0-DaP9Gsy2yQ86blThQ6OwA6
    wai-3.2.4-8IuM47VEJ125o9XLrilMYU
    wai-cors-0.2.7-9gQF0Vc8619HLCHvga9nM1
    wai-extra-3.1.13.0-AE6x2XFGjDgE5EKRKcZBRs
    warp-3.3.25-EVbobsJtri1DLiqF3W27ZB

haddock-interfaces:
    "/Users/keermanipamisetty/Desktop/NDVI ANALYSIS/backend/.stack-work/install/aarch64-osx/2ad67822f177c4de4acf7e19b26519c713ed91bc5171365321467f2f3a5e7417/9.4.8/doc/ndvi-backend-0.1.0.0/ndvi-backend.haddock"

haddock-html:
    "/Users/keermanipamisetty/Desktop/NDVI ANALYSIS/backend/.stack-work/install/aarch64-osx/2ad67822f177c4de4acf7e19b26519c713ed91bc5171365321467f2f3a5e7417/9.4.8/doc/ndvi-backend-0.1.0.0"
